### ISSUE TITLE
Unable to connect frontend to and backend 

### ISSUE THREAD

**Issue by shreyesbenak** [ThomasOliver545/Blog-with-NestJS-and-Angular#39]
[webpack-dev-server] [HPM] Error occurred while proxying request localhost:4200/api/blog-entries?page=1&limit=10 to http://api:3000/ [ENOTFOUND] (https://nodejs.org/api/errors.html#errors_common_system_errors)

**Comment by ThomasOliver545** [comment]
How did you start it?
Did you use docker-compose and read the Readme?

**Comment by novakand** [comment]
Without Docker Error occurred while trying to proxy: localhost:4200/api/users?

**Comment by ThomasOliver545** [comment]
Well if you start it without docker, then you have to adjust the paths.
It's all explained in the readme.
