### ISSUE TITLE
Tag commit for each video

### ISSUE THREAD

**Issue by SSmale** [ThomasOliver545/Blog-with-NestJS-and-Angular#6]
Hi,

Love the series so far, it would be great to take the commit with the video number to make it easier to find

**Comment by ajitsinghkaler** [comment]
Hi @SSmale you can already do that from the commit history the commit names are done very well and are really easy to find

**Comment by SSmale** [comment]
Thanks. I found it difficult to jump between commits when you want to compare changes between videos, especially in the few cases where some fixes were made after the branch was merged in.

**Comment by ThomasKi93** [comment]
Hi, i will try to stick stronger to the process.
But the plan is always, to have one story per video(s). And then commit these changes with the prefix.
